[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "majava"
version = "0.1.0"
dependencies = [
  "pytest"
]
optional-dependencies.tests =  ["flake8"]

[project.entry-points.pytest11]
myproject = "majava.pytplug"
