name: CI Checks

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    - name: Install
      run: pip install -e './[tests]'
    
    - name: Run flake8
      run: flake8 .
    
    - name: Run tests
      run: pytest
